kind: Service
apiVersion: v1
metadata:
  labels:
    app: maksavelat
  name: maksavelat
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: maksavelat

